const CACHE_PREFIX = 'admission-hub-shell-';
const BUILD_ID = 'v266-profile-v11-20260915';
const CACHE_NAME = `${CACHE_PREFIX}${BUILD_ID}`;
const VERSION_HEADER = 'X-Admission-Hub-Build';
const DOCUMENT_NETWORK_TIMEOUT_MS = 2500;
// A stalled asset connection must never hang a script/style load forever.
const STATIC_ASSET_TIMEOUT_MS = 12000;
const isCurrentBuild = response => response && response.headers && response.headers.get(VERSION_HEADER) === BUILD_ID;
function markBuild(response) {
  if (!response || !response.ok) return response;
  const headers = new Headers(response.headers);
  headers.set(VERSION_HEADER, BUILD_ID);
  return response.clone().blob().then(blob => new Response(blob, {status: response.status, statusText: response.statusText, headers}));
}
const APP_SHELL = [
  './index.html',
  './manifest.json',
  './manifest.webmanifest',
  './dashboard-v2.css?v=dash2f11-clean',
  './3d-loader.css?v=3d-v2',
  './session-persist.js?v=session-v2',
  './account-access.css?v=20260916-account-entry-v5',
  './institutions-bd.js?v=bd-institutions-v2',
  './account-access.js?v=20260916-account-entry-v5',
  './academic-catalog.js?v=acad-cat-v2',
  './profile-ui.js?v=profile-v11',
  './profile-ui.css?v=profile-v11',
  './data-protection.js?v=dp-v3-fastboot',
  './dashboard-v2.js?v=dash2f12-clean',
  './ai-agent-chat.js?v=agent-f1-ui-chatv17-clean',
  './icons/icon-192.png',
  './icons/icon-512.png'
];

// SHA-256 of every APP_SHELL asset (generated by scripts/sw-manifest.mjs).
// A truncated/corrupt download is NEVER written to the shell cache.
const ASSET_DIGESTS = {
/* sw-manifest:start */
  "./index.html": "d5d46f7b41f641f2e2831e426b3b23132717905996dc6bcb8e506a2db606dceb",
  "./manifest.json": "11a85ae594fc629b11605daeda3f9afe4ef95215a55a29f9cc423314bfb275a4",
  "./manifest.webmanifest": "5be476009a140eabd088bd972bd4d345b9c4f4a055cd6e4f08774b9cb4afaf52",
  "./dashboard-v2.css?v=dash2f11-clean": "0c20c3a97ec99ca00690f3dce037f44a00fe3fa917a9b2f1f19b11acc02cda9f",
  "./3d-loader.css?v=3d-v2": "43ca21b0a41be5d223c317fd63582f19ff6ffab5d010639ef26349464550da63",
  "./session-persist.js?v=session-v2": "99f3d1f49f6d5714fd25f1c12b2aa978ca97a009d6caba9a690a0442d082593c",
  "./account-access.css?v=20260916-account-entry-v5": "250cf804428c240f31132872485aa8d5984f2f489ea8fb30038aa3884ec58913",
  "./institutions-bd.js?v=bd-institutions-v2": "602c5549515e8207ad152b948ca9b8fe3ad0fbe429afb56380e4e21b662f779d",
  "./account-access.js?v=20260916-account-entry-v5": "3253207302525eec177e576019785909a601bfd848e9ff206f5d72f7e25a3389",
  "./academic-catalog.js?v=acad-cat-v2": "598c5fb79050ec9729fed6d6749675e85888f1d1b2f8836dbc509b56b18e4c43",
  "./profile-ui.js?v=profile-v11": "54c7c42d363fb7306539c983f3bbee612b1641d584b4ff9e0868daa12bbb4754",
  "./profile-ui.css?v=profile-v11": "cf77d9ff315e3b7d327d518eabab36c6818973ad942296da75214799675b932c",
  "./data-protection.js?v=dp-v3-fastboot": "359dc907ade4bcb3a6a722385969ebb6af47f7e436e6cdf2cce0dd6b7343723d",
  "./dashboard-v2.js?v=dash2f12-clean": "fe480f999c5d19c380752c8ceed5603dc9a31be2c5cf254cd45e23e233fb45f4",
  "./ai-agent-chat.js?v=agent-f1-ui-chatv17-clean": "9c177d878cbd0cdb7b74617f545cb41ce790041c492c7cbb2368230c277de544",
  "./icons/icon-192.png": "777ce5566fbeff0f2e384c787c8dde4f47d7c869e455c6e577a503decd4f1683",
  "./icons/icon-512.png": "86459109582f82b1d891a3e5a82723fefd21a3c65e9d0d22ab4dae33bb540520",
/* sw-manifest:end */
};

const isDocumentRequest = request => request.mode === 'navigate' || request.destination === 'document';

async function cacheNetworkResponse(request, response) {
  if (!response || !response.ok) return response;
  try {
    const cache = await caches.open(CACHE_NAME);
    const versioned = await markBuild(response);
    await cache.put(request, versioned.clone());
  } catch (_) {
    // Cache failures must never block the fresh network response.
  }
  return response;
}

async function offlineFallback(request) {
  const cached = await caches.match(request);
  if (cached && isCurrentBuild(cached)) return cached;

  if (isDocumentRequest(request)) {
    const shell = await caches.match('./index.html');
    if (shell && isCurrentBuild(shell)) return shell;
    const shellUrl = new URL('./index.html', self.location.href).href;
    const fallback = await caches.match(shellUrl);
    return fallback && isCurrentBuild(fallback) ? fallback : Response.error();
  }

  return Response.error();
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await Promise.all(APP_SHELL.map(async asset => {
      try {
        const url = new URL(asset, self.location.href).href;
        const request = new Request(url, {cache: 'reload'});
        const response = await fetch(request, {cache: 'no-store'});
        if (!response.ok) return;
        // Digest gate: a truncated body has the wrong SHA-256 — never cache it.
        const expected = ASSET_DIGESTS[asset];
        if (expected) {
          const blob = await response.clone().blob();
          const digest = await blob.digest('SHA-256');
          const hex = Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('');
          if (hex !== expected) return; // poisoned download — fetch fresh at runtime
        }
        await cacheNetworkResponse(request, response);
      } catch (_) {
        // The worker can still activate if an optional shell asset is unavailable.
      }
    }));

    // Activate this worker immediately; do not wait for old tabs to close.
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter(key => key !== CACHE_NAME)
        .map(key => caches.delete(key))
    );

    // Take control without navigating/reloading open iOS clients. Forced client
    // navigation during activation could restart boot and appear as a loader loop.
    await self.clients.claim();
  })());
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    event.waitUntil(self.skipWaiting());
    return;
  }
  if (event.data && event.data.type === 'VERSION_CHECK') {
    event.ports?.[0]?.postMessage({type:'VERSION_CHECK_RESULT', buildId:BUILD_ID, cacheName:CACHE_NAME});
  }
});

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const requestUrl = new URL(request.url);
  if (requestUrl.origin !== self.location.origin) return;

  // The privileged control page is network-only and must never be replaced by or
  // written into the offline application shell.
  if (requestUrl.pathname === '/verification-control-center' || requestUrl.pathname === '/verification-control-center.html') {
    event.respondWith(fetch(request, { cache: 'no-store' }).catch(() => new Response('Control Center requires an internet connection.', {
      status: 503,
      headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' }
    })));
    return;
  }

  // Authentication responses are always live and are never written to the PWA cache.
  if (requestUrl.pathname.startsWith('/api/auth/')) {
    event.respondWith(fetch(request, { cache: 'no-store' }).catch(() => new Response(JSON.stringify({
      ok: false, error: { code: 'OFFLINE', message: 'অ্যাকাউন্ট সেবার জন্য ইন্টারনেট সংযোগ প্রয়োজন।' }
    }), {
      status: 503,
      headers: { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' }
    })));
    return;
  }

  event.respondWith((async () => {
    // Documents are bounded network-first. This prevents a healthy online browser
    // from being trapped forever on an old Auth UI while retaining a fast offline
    // shell fallback well inside the five-second startup budget.
    if (isDocumentRequest(request)) {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), DOCUMENT_NETWORK_TIMEOUT_MS);
      try {
        const response = await fetch(request, { cache: 'no-store', signal: controller.signal });
        const contentType = response.headers.get('content-type') || '';
        if (!response.ok || !contentType.includes('text/html')) throw new Error('DOCUMENT_UNAVAILABLE');
        return await cacheNetworkResponse(request, response);
      } catch (_) {
        return offlineFallback(request);
      } finally {
        clearTimeout(timeout);
      }
    }

    const staticAsset = request.destination === 'script' || request.destination === 'style' || request.destination === 'image' || request.destination === 'font' || /\.(?:js|css|json|png|jpg|jpeg|webp|svg|ico|woff2?)(?:$|\?)/i.test(requestUrl.pathname + requestUrl.search);
    if (staticAsset) {
      const cached = await caches.match(request);
      if (cached && isCurrentBuild(cached)) return cached;
      // Bounded + cache:'no-store': the browser HTTP cache is NEVER consulted
      // (a truncated body cached during a network blip would be served on every
      // load otherwise — owner bug v262/v263). The shell cache is the only cache.
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), STATIC_ASSET_TIMEOUT_MS);
      try {
        return await cacheNetworkResponse(request, await fetch(request, { cache: 'no-store', signal: controller.signal }));
      } catch (_) {
        return offlineFallback(request);
      } finally {
        clearTimeout(timer);
      }
    }
    try {
      // Dynamic same-origin GET requests remain network-first.
      const response = await fetch(request, {cache: 'no-store'});
      const contentType = response.headers.get('content-type') || '';
      if (isDocumentRequest(request) && !contentType.includes('text/html')) return offlineFallback(request);
      return cacheNetworkResponse(request, response);
    } catch (_) {
      return offlineFallback(request);
    }
  })());
});

// v107 — Web Push display + notification click routing
self.addEventListener('push', (event) => {
  let data = {};
  try { data = event.data.json(); } catch (_) {}
  event.waitUntil(self.registration.showNotification(String(data.title || 'Admission Hub 🔔'), {
    body: String(data.body || ''), tag: String(data.tag || 'admission-hub'), renotify: true, data: { url: data.url || './' }
  }));
});
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || './';
  event.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
    for (const client of list) { if ('focus' in client) { try { client.navigate(url); } catch (_) {} return client.focus(); } }
    return self.clients.openWindow(url);
  }));
});
